# Generated by Django 4.2.1 on 2023-05-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicportal', '0002_myfileupload_remove_song_album_delete_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfileupload',
            name='my_file',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
