# Generated by Django 4.2.1 on 2023-05-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicportal', '0005_alter_myfileupload_my_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfileupload',
            name='my_file',
            field=models.FileField(upload_to='files/audio/'),
        ),
    ]
