# Generated by Django 4.2.1 on 2023-06-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicportal', '0013_alter_myfileupload_my_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfileupload',
            name='image',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
    ]
